In [1]:
import numpy as np

In [4]:
data = [np.random.standard_normal() for i in range(7)]

In [13]:
print(data)

[-2.6188818090373864, -0.5020039722624872, 0.14299651852652218, -1.2682263684045016, 0.5346778727120516, -0.12052833774878907, 0.16082979749169451]


In [22]:
an_apple = 27

In [23]:
an_example = 42

In [34]:
b = [1, 2, 3]

In [37]:
import datetime

In [41]:
datetime.date

datetime.date

In [54]:
print?

In [55]:
def add_numbers(a,b):
    return a + b

In [58]:
add_numbers?

In [59]:
np.*load*?

In [60]:
a = b

In [61]:
b

[1, 2, 3, 1, 2, 3]

In [62]:
a.append(4)

In [63]:
b

[1, 2, 3, 1, 2, 3, 4]

In [64]:
a

[1, 2, 3, 1, 2, 3, 4]

In [70]:
isinstance(a, (tuple ,list))

True

In [2]:
a = "foo"
getattr(a, "split")

<function str.split(sep=None, maxsplit=-1)>

In [74]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError:
        return False

In [77]:
isiterable(44)

False

In [78]:
isiterable(a)

True

In [5]:
b = a.replace("foo", "modified foo")

In [6]:
b

'modified foo'

In [8]:
a = list(a)
a

['f', 'o', 'o']

In [9]:
a[1] = 'i'

In [10]:
a = str(a)

In [11]:
a

"['f', 'i', 'o']"

In [2]:
template = "{0:.2f} {1:s} are worth US${2:d}"

In [3]:
template.format(88.46, "Argantine Pessos", 1)

'88.46 Argantine Pessos are worth US$1'

In [4]:
amount = 88.46
currency = "Argantine Pessos"
x = 1

In [14]:
result = f"{amount} {currency} is worth US${x} "

In [15]:
print(result)

88.46 Argantine Pessos is worth US$1 


In [25]:
val = "رسم"

In [26]:
val_utf8 = val.encode("utf-8")

In [27]:
val_utf8

b'\xd8\xb1\xd8\xb3\xd9\x85'

In [28]:
type(val_utf8)

bytes

In [30]:
from datetime import datetime, date, time

In [31]:
dt = datetime(2011, 10, 29, 20, 30, 21)

In [33]:
dt.day

29

In [34]:
dt.minute

30

In [36]:
dt.date()

datetime.date(2011, 10, 29)

In [37]:
dt.time()

datetime.time(20, 30, 21)

In [40]:
dt.strftime("%Y-%m-%d %H:%M")

'2011-10-29 20:30'

In [41]:
dt.strptime("20091030", "%Y%m%d")

datetime.datetime(2009, 10, 30, 0, 0)

In [42]:
dt_hour = dt.replace(minute = 0, second = 0)

In [43]:
dt_hour

datetime.datetime(2011, 10, 29, 20, 0)

In [44]:
dt2 = datetime(2011, 11, 15, 22, 30)

In [48]:
delta = dt2 - dt

In [49]:
delta

datetime.timedelta(days=17, seconds=7179)

In [50]:
dt

datetime.datetime(2011, 10, 29, 20, 30, 21)

In [51]:
delta + dt

datetime.datetime(2011, 11, 15, 22, 30)

In [54]:
list(range(5, 0, -1))

[5, 4, 3, 2, 1]

In [1]:
seq = [1, 2, 3, 4]

In [60]:
for i in range(len(seq)):
    print(f"element {i}: {seq[i]}")

element 0: 1
element 1: 2
element 2: 3
element 3: 4


In [2]:
type(seq)

list

In [3]:
type(seq) is list

True

In [4]:
tup = 4, 6 ,9

In [9]:
tup = list(tup)

In [12]:
type(tup)

list

In [13]:
tuple(tup)

(4, 6, 9)

In [16]:
name = 'moaz'
name = tuple(name)

In [17]:
name

('m', 'o', 'a', 'z')

In [20]:
('a', 'b', 'c') + (1, 2, 3) * 4

('a', 'b', 'c', 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3)

In [22]:
a, b, c, d = name

In [23]:
a

'm'

In [24]:
a, b, c, d = d, c, b, a

In [26]:
a

'z'

In [27]:
a, b, *rest = name

In [30]:
type(rest)

list

In [31]:
type(name)

tuple

In [33]:
rest.count('z')

1

In [34]:
gen = range(10)

In [35]:
gen

range(0, 10)

In [38]:
gen = list(gen)

In [39]:
gen.insert(1, 1)

In [44]:
gen

[1, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
0 in gen

False

In [46]:
while 1 in gen:
    gen.remove(1)

In [47]:
gen

[2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
tuples = zip(range(5), reversed(range(5)))

In [55]:
tuples

In [57]:
mapping = dict(tuples)

In [59]:
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [2]:
words = ['apple', 'bat', 'bar', 'atom', 'book']

In [24]:
by_letter = {}

In [4]:
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)

In [5]:
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [25]:
for word in words:
    letter = word[0]
    by_letter.setdefault(letter, []).append(word)

In [26]:
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [28]:
from collections import defaultdict

In [29]:
by_letter = defaultdict(list)

In [30]:
by_letter

defaultdict(list, {})

In [31]:
for word in words:
    by_letter[word[0]].append(word)

In [33]:
by_letter

defaultdict(list, {'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']})

In [34]:
hash("hey")

-5223373756686841606

In [36]:
a = {1, 2, 3, 4, 5}

In [37]:
type(a)

set

In [38]:
a.add(6)

In [39]:
a

{1, 2, 3, 4, 5, 6}

In [32]:
a.clear()

In [33]:
a

set()

In [34]:
a.remove(1)

KeyError: 1

In [40]:
a

{1, 2, 3, 4, 5, 6}

In [41]:
a.pop()

1

In [42]:
b = {7, 8, 9, 10, 11}

In [43]:
a.union(b)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

In [19]:
a.update(b)

In [22]:
a & b 

{7, 8, 9, 10, 11}

In [25]:
a.intersection_update(b)

In [26]:
a

{7, 8, 9, 10, 11}

In [44]:
a.difference(b)

{2, 3, 4, 5, 6}

In [45]:
a.isdisjoint(b)

True

In [46]:
a ^ b

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

In [47]:
a

{2, 3, 4, 5, 6}

In [49]:
b

{7, 8, 9, 10, 11}

In [51]:
a ^= b

In [52]:
a

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

In [53]:
b

{7, 8, 9, 10, 11}

In [55]:
a <= b

False

In [57]:
a >= b

True

In [58]:
c = 5
d = 6

In [59]:
c.union(d)

AttributeError: 'int' object has no attribute 'union'

In [60]:
c = a.copy()

In [61]:
c

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

In [62]:
c = {[1], 5, 6}

TypeError: unhashable type: 'list'

In [77]:
for index, value in enumerate(c):
    x[index] = value

In [78]:
x

{0: 2, 1: 3, 2: 4, 3: 5, 4: 6, 5: 7, 6: 8, 7: 9, 8: 10, 9: 11}

In [76]:
x.clear()

In [4]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [5]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']

In [6]:
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [82]:
map?

In [9]:
set(map(len, strings))

{1, 2, 3, 4, 6}

In [10]:
len(strings[1])

2

In [11]:
loc_mapping = {value : index for index, value in enumerate(strings)}

In [12]:
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [14]:
All_data = [['Join', 'Maria', 'Michael', 'Mary', 'Steven'], ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

In [16]:
result = [name for names in All_data for name in names if name.count('a') >= 2]

In [17]:
result

['Maria', 'Maria', 'Natalia']

In [18]:
some_tuples = ((1, 2, 3), (4, 5, 6), (7, 8, 9))

In [19]:
flattened = [x for tup in some_tuples for x in tup]

In [20]:
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
nested = [[x for x in tup] for tup in some_tuples]

In [23]:
nested

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [71]:
def func0():
    a = []
    for i in range(5):
        a.append(i)

In [28]:
import re

In [60]:
states = ['   alabama', 'georgia !']

In [61]:
def clean_strings(strings):
    result = []
    for value in strings:
        value = re.sub('[!?#]', '', value)
        value = value.strip()
        value = value.title()
        result.append(value)
    return result

In [62]:
clean_strings(states)

['Alabama', 'Georgia']

In [63]:
def remove_panctuation(value):
    return re.sub("[!?#]", "", value)

In [78]:
clean_ops = [remove_panctuation, str.strip, str.title]

In [79]:
def clean_strings(strings, ops):
    result = []
    for value in strings:
        for func in ops:
            value = func(value)
        result.append(value)
    return result

In [81]:
set(clean_strings(states, clean_ops))

{'Alabama', 'Georgia'}

In [86]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

In [87]:
ints = [4, 0, 1, 5, 6]

In [88]:
apply_to_list(ints, lambda x: x * 2)

[8, 0, 2, 10, 12]

In [89]:
[x * 2 for x in ints ]

[8, 0, 2, 10, 12]

In [92]:
x = 'hey'
len(set(x))

3

In [97]:
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']

In [98]:
#in order to sort them according to their distinct letters.
strings.sort(key = lambda x: len(set(x)))

In [99]:
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

In [1]:
some_dict = {'a' :1, 'b': 2, 'c': 3}

In [2]:
dict_iterator = iter(some_dict)

In [3]:
dict_iterator

In [15]:
def squares(n=10):
    print(f"Generating squares from 1 to {n  ** 2}")
    for i in range(1, n+1):
        yield i ** 2

In [16]:
gen = squares()

In [17]:
gen

<generator object squares at 0x00000283CBDA3A50>

In [18]:
for x in gen:
    print(x, end=" ")

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

In [20]:
gen = (x**2 for x in range(100))

In [21]:
gen

<generator object <genexpr> at 0x00000283CBDB0510>

In [22]:
sum(x**2 for x in range(100))

328350

In [23]:
dict((i, i**2) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [33]:
import itertools as i

In [29]:
def first_letter(x):
    return x[0]

In [43]:
names = ['alan', 'adam', 'wes', 'will', 'albert', 'steven']

In [31]:
for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names))

a ['alan', 'adam']
w ['wes', 'will']
a ['albert']
s ['steven']


In [35]:
x = i.chain(names, names)

In [36]:
x

In [38]:
help(i.chain)

Help on class chain in module itertools:

class chain(builtins.object)
 |  chain(*iterables) --> chain object
 |  
 |  Return a chain object whose .__next__() method returns elements from the
 |  first iterable until it is exhausted, then elements from the next
 |  iterable, until all of the iterables are exhausted.
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  __setstate__(...)
 |      Set state information for unpickling.
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  __class_getitem__(...) from builtins.type
 |      See PEP 585
 |  
 |  from_iterable(iterable, /) from builtins.type
 |      Alternative chain() constructor taking a single iterable argument tha

In [44]:
names

['alan', 'adam', 'wes', 'will', 'albert', 'steven']

In [52]:
for a in i.combinations(range(5), 2):
    print(a)

(0, 1)
(0, 2)
(0, 3)
(0, 4)
(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [53]:
for a in i.permutations(range(5), 2):
    print(a)

(0, 1)
(0, 2)
(0, 3)
(0, 4)
(1, 0)
(1, 2)
(1, 3)
(1, 4)
(2, 0)
(2, 1)
(2, 3)
(2, 4)
(3, 0)
(3, 1)
(3, 2)
(3, 4)
(4, 0)
(4, 1)
(4, 2)
(4, 3)


In [54]:
def attempt_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return x

In [59]:
attempt_float((1, 3))

(1, 3)

In [60]:
path = "something/somewhere/me"

In [61]:
f = open(path, encoding = "utf-8")

FileNotFoundError: [Errno 2] No such file or directory: 'something/somewhere/me'

In [ ]:
#this closes the file right after reading its lines.
with open(path, encoding="utf-8") as f:
    lines = [x.rstrip() for x in f]

In [68]:
import sys

In [69]:
sys.getdefaultencoding()

'utf-8'

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)

In [3]:
my_list = list(range(1_000_000))

In [4]:
%timeit my_arr2 = my_arr * 2

1.05 ms ± 19.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

54.4 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [7]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [9]:
data * data

array([[2.250e+00, 1.000e-02, 9.000e+00],
       [0.000e+00, 9.000e+00, 4.225e+01]])

In [10]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [17]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
arr2 = np.array(data2)

In [20]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [40]:
a = np.zeros((10, 5))

In [44]:
np.empty_like(arr1)

array([ 3. ,  0.2,  6. ,  6. , 13. ])

In [45]:
np.full?

In [46]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [47]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [48]:
arr1.dtype

dtype('float64')

In [49]:
arr2.dtype

dtype('int32')

In [53]:
arr3 = np.array([1, -2, 5, 6])

In [55]:
arr3 = arr3.astype(np.uint8)

In [56]:
arr3

array([  1, 254,   5,   6], dtype=uint8)

In [58]:
numeric_strings = np.array(["1.3", "4", "6.3"], dtype = np.string_)

In [59]:
numerics = numeric_strings.astype(np.float64)

In [60]:
numerics

array([1.3, 4. , 6.3])

In [61]:
numerics.dtype

dtype('float64')

In [62]:
calibers = np.arange(10)

In [63]:
calibers.astype(numerics.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [71]:
lst = [x for x in range(10)]

In [72]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [73]:
lst[5:8]

[5, 6, 7]

In [78]:
lst[5:8] = [10, 10, 10]

In [79]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [80]:
arr2[1,2]

6

In [81]:
ist = list(arr2)

In [82]:
ist

[array([1, 2, 3]), array([4, 5, 6])]

In [83]:
ist = [[list(ist[0])], [list(ist[1])]]

In [84]:
ist

[[[1, 2, 3]], [[4, 5, 6]]]

In [87]:
ist[0][0]

[1, 2, 3]

In [94]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [95]:
data = np.array([[4, 6], [0,2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [96]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [97]:
data[names == "Bob"]

array([[4, 6],
       [0, 0]])

In [99]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [101]:
mask = (names == 'Bob') | (names == 'Will')

In [104]:
data[mask]

array([[ 4,  6],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [105]:
rarr = np.empty((8, 4))

In [106]:
for i in range(8):
    rarr[i] = i

In [107]:
rarr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [108]:
rarr[[7, 4, 1, 3]]

array([[7., 7., 7., 7.],
       [4., 4., 4., 4.],
       [1., 1., 1., 1.],
       [3., 3., 3., 3.]])

In [109]:
np.arange(8*4).reshape(8, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [110]:
rarr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [111]:
np.dot(rarr.T, rarr)

array([[140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.]])

In [114]:
rarr @ rarr.T

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   4.,   8.,  12.,  16.,  20.,  24.,  28.],
       [  0.,   8.,  16.,  24.,  32.,  40.,  48.,  56.],
       [  0.,  12.,  24.,  36.,  48.,  60.,  72.,  84.],
       [  0.,  16.,  32.,  48.,  64.,  80.,  96., 112.],
       [  0.,  20.,  40.,  60.,  80., 100., 120., 140.],
       [  0.,  24.,  48.,  72.,  96., 120., 144., 168.],
       [  0.,  28.,  56.,  84., 112., 140., 168., 196.]])

In [115]:
rarr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [121]:
np.swapaxes?

In [122]:
samples = np.random.standard_normal(size = (4, 4))

In [123]:
samples

array([[-0.21746413, -0.88544607,  0.02963121, -1.06034186],
       [-0.31087718, -1.9767235 , -1.11119007, -0.99704728],
       [-0.01098025,  0.30685523,  0.47129791, -1.18492974],
       [-0.74706631,  0.32642464,  0.0683995 ,  0.20139014]])

In [125]:
from random import normalvariate

In [126]:
N = 1_000_000

In [128]:
%timeit smaples = [normalvariate(0,1) for _ in range(N)]

627 ms ± 34.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [129]:
%timeit np.random.standard_normal(N)

19.4 ms ± 167 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [131]:
rng = np.random.default_rng(seed = 12345)

In [132]:
data = rng.standard_normal((2,3))

In [135]:
type(rng)

numpy.random._generator.Generator

In [136]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [137]:
np.exp(arr)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [143]:
arr = rng.standard_normal(7) *6

In [147]:
remainder, qoutient = np.modf(arr)

In [148]:
remainder

array([ 0.41318965, -0.80171904, -0.36413711,  0.73306607, -0.5400088 ,
        0.45514509,  0.39387397])

In [149]:
qoutient

array([ 5., -2., -0.,  4., -7.,  3.,  8.])